version: '3.9'
services:
  orchestrator:
    image: docker_gotham_orchestrator_img:latest
    volume: 
        - install_orchestrator.sh:/opt/GOTHAM/Install/docker
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root


