version: '3.9'
services:
  orchestrator: 
    build: docker_gotham_orchestrator
    #image: orchestrator_img
    #volumes: 
        - /opt/GOTHAM/Install/
    #restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root