version: '3.9'
services:
  orchestrator:
    image: docker_gotham_orchestrator
    #volumes: 
    #    - install_orchestrator.sh:~/GOTHAM/Install/
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root