version: '3.9'
services:
  orchestrator: 
    build: /home/petibonum/GOTHAM/Install/docker_gotham_orchestrator
    volumes: 
        - /opt/GOTHAM/Install/
    #restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root