version: '3.9'
services:
  orchestrator: 
    build: docker_gotham_orchestrator
    image: orchestrator_img
    volumes: 
        - docker_gotham_orchestrator:/opt/GOTHAM/Install/docker
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root