version: '3.9'
services:

  ## ORCHESTRATOR
  #orchestrator: 
    build:
    context: .
      dockerfile: /home/petibonum/GOTHAM/Install/docker_gotham_orchestrator
    environment:
      GOTHAM_HOME: "/opt/GOTHAM/"
      GOTHAM_GIT: "https://github.com/Spit22/GOTHAM"
      EXEC_BRANCH: "remotes/origin/dev_V1"
      MARIADB_ROOT_PASSWORD=root
    deploy:
      mode: replicated
      replicas: 1
  
  ## SERVER
  server:
    build:
      context: .
      dockerfile: /home/petibonum/GOTHAM/Install/docker_gotham_server
    deploy:
      mode: replicated
      replicas: 1

  ## DATA-CENTER
  dc:
    build:
      context: .
      dockerfile: /home/petibonum/GOTHAM/Install/docker_gotham_dc
    deploy:
      mode: replicated
      replicas: 1


  